routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);

Route::get('/blog/{post}',[
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);


Route::get('/category/{category}' ,[
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/author/{author}' ,[
    'uses' => 'BlogController@author',
    'as' => 'author'
]);


Auth::routes();

Route::get('/home', 'Backend\HomeController@index')->name('home');

// Route::get('/backend/blog/create' , 'Backend\BlogController@create')->name('/backend/blog/create');

// Route::get('/backend/blog/' , 'Backend\BlogController@index')->name('/backend/blog/index');

Route::resource('/backend/blog/' , 'Backend\BlogController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{
    protected $dates= ['published_at'];
    public function author()
    {
        return $this->belongsTo(User::class);
    }
    
    public function category(){
        
        return $this->belongsTo(Category::class);

    }

    public function getImageUrlAttribute($value){

        $imageUrl = "";

        if ( ! is_null($this->image) )
        {

            $imagePath = public_path(). "/img/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("img/" . $this->image);

        }

        return $imageUrl;
    }

    public function getImageUrlThumbAttribute($value){

        $imageUrl = "";

        if ( ! is_null($this->image) )
        {
            $ext = substr(strrchr($this->image, '.'), 1);

            $thumbnail = str_replace(".{$ext}" ,"_thumb.{$ext}" , $this->image);
            $imagePath = public_path(). "/img/" . $thumbnail;
            if (file_exists($imagePath)) $imageUrl = asset("img/" . $thumbnail);

        }

        return $imageUrl;
    }


    public function getDateAttribute($value)
    {
        return is_null($this-> published_at) ? '' :$this->published_at ->diffForHumans();
    }

    public function scopeLatestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePopular($query)
    {
     
        return $query->orderBy('view_count', 'desc');
        
    }

    public function scopePublished($query)
    {
        return $query-> where("published_at" , "<=" , carbon :: now());
    }

    public function getBodyHtmlAttribute()
    {
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }
    public function getExcerptHtmlAttribute()
    {
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    public function dateFormatted( $showTimes= false)
    {
        $format = "d/m/y";
        if ($showTimes) $format = $format . "H:i:s";
        return $this->created_at->format($format);
    }
    
    public function publicationLabel()
    {

        if( ! $this->published_at){
            return '<span class="label label-warning">draft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">scheduled</span>';
        } else {
            return '<span class="label label-success">published</span>';
        }

    }  
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GrahamCampbell\Markdown\Facades\Markdown;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','category_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'author_id');
    }

    public function getBioHtmlAttribute()
    {
        return $this->bio ? Markdown::convertToHtml(e($this->bio)) : NULL;
    }
    public function gravatar()
    {
        $email = $this->email;
        $default = "asset('img/matthew.png')";
        $size = 40;

        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?d=" . urlencode( $default ) . "&s=" . $size;
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Post;

class BlogController extends BackendController
{

    protected $limit = 5;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          
        $posts = Post::with('category', 'author')->latest()->paginate($this->limit);
       
        $postCount = Post::count();
        return view('backend.blog.index' , compact('posts' , 'postCount'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //dd('create new blog post');\

        $post = new Post();
        return view('backend.blog.create' , compact('post'));
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        dd('Hello there, i edit stuff');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Post;
use App\Category;
use App\User;

class BlogController extends Controller
{
    protected $limit = 3;

    public function index()
    {
        $posts = Post::with('author')
                        ->latestFirst()
                        ->published()
                        ->simplepaginate($this->limit);  
                        return view("blog.index" , compact('posts'));
        
    }

    public function category(Category $category)
    {

    $categoryName = $category->title;

        
            $posts = $category->posts()
                                ->with('author')
                                ->latestFirst()
                                ->published()
                                ->simplePaginate($this->limit);

        return view("blog.index" , compact('posts' ,'categoryName'));
        
    }

    public function show(Post $post)
    {

        
        $post->increment('view_count');
       return view("blog.show" , compact('post'));
    }

    public function author(User $author)
    {
        $authorName = $author->name;

        
            $posts = $author->posts()
                                ->with('category')
                                ->latestFirst()
                                ->published()
                                ->simplePaginate($this->limit);

        return view("blog.index" , compact('posts' ,'authorName'));
    }
}

resources/views/blog/comments.blade.php
<article class="post-comments">
                  <h3><i class="fa fa-comments"></i> 5 Comments</h3>

                  <div class="comment-body padding-10">
                      <ul class="comments-list">
                          <li class="comment-item">
                              <div class="comment-heading clearfix">
                                  <div class="comment-author-meta">
                                      <h4>John Doe <small>January 14, 2016</small></h4>
                                  </div>
                              </div>
                              <div class="comment-content">
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                  <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                              </div>
                          </li>

                          <li class="comment-item">
                              <div class="comment-heading clearfix">
                                  <div class="comment-author-meta">
                                      <h4>John Doe <small>January 14, 2019</small></h4>
                                  </div>
                              </div>
                              <div class="comment-content">
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                  <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                                  <ul class="comments-list-children">
                                      <li class="comment-item">
                                          <div class="comment-heading clearfix">
                                              <div class="comment-author-meta">
                                                  <h4>John Doe <small>January 14, 2019</small></h4>
                                              </div>
                                          </div>
                                          <div class="comment-content">
                                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                              <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                                          </div>
                                      </li>

                                      <li class="comment-item">
                                          <div class="comment-heading clearfix">
                                              <div class="comment-author-meta">
                                                  <h4>John Doe <small>January 14, 2019</small></h4>
                                              </div>
                                          </div>
                                          <div class="comment-content">
                                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                              <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                                              <ul class="comments-list-children">
                                                  <li class="comment-item">
                                                      <div class="comment-heading clearfix">
                                                          <div class="comment-author-meta">
                                                              <h4>John Doe <small>January 14, 2019</small></h4>
                                                          </div>
                                                      </div>
                                                      <div class="comment-content">
                                                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                                                          <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                                                      </div>
                                                  </li>
                                              </ul>
                                          </div>
                                      </li>
                                  </ul>
                              </div>
                          </li>
                      </ul>

                  </div>

                  <div class="comment-footer padding-10">
                      <h3>Leave a comment</h3>
                      <form>
                          <div class="form-group required">
                              <label for="name">Name</label>
                              <input type="text" name="name" id="name" class="form-control">
                          </div>
                          <div class="form-group required">
                              <label for="email">Email</label>
                              <input type="text" name="email" id="email" class="form-control">
                          </div>
                          <div class="form-group">
                              <label for="website">Website</label>
                              <input type="text" name="website" id="website" class="form-control">
                          </div>
                          <div class="form-group required">
                              <label for="comment">Comment</label>
                              <textarea name="comment" id="comment" rows="6" class="form-control"></textarea>
                          </div>
                          <div class="clearfix">
                              <div class="pull-left">
                                  <button type="submit" class="btn btn-lg btn-success">Submit</button>
                              </div>
                              <div class="pull-right">
                                  <p class="text-muted">
                                      <span class="required">*</span>
                                      <em>Indicates required fields</em>
                                  </p>
                              </div>
                          </div>
                      </form>
                  </div>

              </article>

resources/views/blog/index.blade.php
@extends ('layouts.main')


@section ('content')

<div class="container">

        <div class="row">
            <div class="col-md-8">

                @if(! $posts->count() )
                    <div class="alert alert-warning">
                        <p>No Post Found </p> 
                        <a href="#">click here to contribute on the topic</a>
                        
                    </div>

                @else 

                @if (isset($categoryName))

                    <div class="alert alert-info">
                        <p>Category: <strong>{{ $categoryName }}</strong></p>
                    </div>

                @endif

                @if (isset($authorName))

                    <div class="alert alert-info">
                        <p>All Posts By: <strong>{{ $authorName }}</strong></p>
                    </div>

                @endif

                @foreach($posts as $post )

                <article class="post-item">

                       @if($post->image_url)

                            <div class="post-item-image">
                                <a href="{{ route('blog.show' , $post->slug) }}">
                                    <img src="{{$post->image_url}}" alt="I am NOt Working too">
                                </a>
                            </div>

                        @endif
                        
                    <div class="post-item-body">
                        <div class="padding-10">
                            
                            <h2><a href="{{ route('blog.show' , $post->slug) }}">{{$post->title}}</a></h2>
                            {!! $post->excerpt_html !!}
                            
                        </div>

                        <div class="post-meta padding-10 clearfix">
                            <div class="pull-left">
                                <ul class="post-meta-group">
                                <li><i class="fa fa-user"></i><a href="{{route('author' , $post->author->slug)}}"> {{$post->author->name}}</a></li>
                                    <li><i class="fa fa-clock-o"></i><time>{{$post->date}}</time></li>
                                <li><i class="fa fa-tags"></i><a href="{{ route('category' , $post->category->slug) }}">{{$post->category->title}}</a></li>
                                    <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                                </ul>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('blog.show' , $post->slug) }}">Continue Reading &raquo;</a>
                            </div>
                        </div>
                    </div>
                </article>

            @endforeach
                @endif

            
                <nav>
                 {{ $posts->links() }}
            </div>
            
            @include ('layouts.sidebar')

        </div>
    </div>



@endsection 

resources/views/blog/show.blade.php
@extends ('layouts.main')


@section ('content')

<div class="container">

        <div class="row">
          <div class="col-md-8">
              <article class="post-item post-detail">

              @if($post->image_url)
                  <div class="post-item-image">
                     
                          <img src="{{$post->image_url}}" alt="{{$post -> title}}">
                     
                  </div>

                @endif

                  <div class="post-item-body">
                      <div class="padding-10">
                          <h1>{{$post->title}}</h1>

                          <div class="post-meta no-border">
                              <ul class="post-meta-group">
                              <li><i class="fa fa-user"></i><a href="{{ route('author' , $post->author->slug)}}">{{$post->author->name}}</a></li>
                                  <li><i class="fa fa-clock-o"></i><time>{{$post->date}}</time></li>
                              <li><i class="fa fa-tags"></i><a href="{{ route('category' , $post->category->slug)}}">{{$post->category->title}}</a></li>
                                  <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
                              </ul>
                          </div>

                         {!! $post->body_html !!}
                      </div>
                  </div>
              </article>

              <article class="post-author padding-10">
                  <div class="media">
                    <div class="media-left">
                    <a href="{{ route('author' , $post->author->slug) }}">
                      <img alt="{{ $post->author->name}}" src="/img/matthew.png" class="media-object">
                      {{-- //{{$post->author->gravatar() }} --}}

                        {{-- remember to use  gravatar to get the image --}}

                      </a>
                    </div>
                    <div class="media-body">
                      <h4 class="media-heading"><a href="{{ route('author' , $post->author->slug)}}">{{$post->author->name}}</a></h4>
                      <div class="post-author-count">
                        <a href="{{ route('author' , $post->author->slug)}}">
                            <i class="fa fa-clone"></i>

                            <?php $postCount = $postCount = $post->author->posts()->published()->count() ?>
                            
                            {{ $postCount}} {{str_plural('post' , $postCount)}}
                        </a>
                      </div>
                      {!! $post->author->bio_html !!}
                    </div>
                  </div>
              </article>

    <!-- comments will go here dumbass -->
          </div>
            
            @include ('layouts.sidebar')

        </div>
    </div>



@endsection 